/* QuickTrade Life — 직업별·장 마감 월말 이벤트 */
(function(root){'use strict';
const C=(id,cat,title,desc,jobs,options,emoji='📋')=>({id:'career_'+id,cat,emoji,title,desc,cond:x=>!jobs||jobs.includes(x.job),options});
const CAREER_EVENTS=[
 C('bonus','job','예상 밖의 성과급','팀 실적이 좋아 특별 성과급 대상이 됐습니다.',null,[{text:'전액 투자한다',effects:{cash:[1000000,5000000],happy:2},outcome:'보너스를 투자 계좌로 옮겼다.'},{text:'절반은 저축하고 절반은 쓴다',effects:{cash:[500000,2500000],happy:8},outcome:'미래와 현재를 함께 챙겼다.'},{text:'동료들에게 한턱낸다',effects:{cash:[-500000,500000],happy:12,charm:3},outcome:'통장은 가벼워졌지만 평판은 좋아졌다.'}],'💰'),
 C('layoff','job','희망퇴직 공고','회사가 큰 위로금을 걸고 희망퇴직 신청을 받습니다.',['office','dev','designer','sales','researcher','factory'],[{text:'남아서 버틴다',effects:{happy:-4},outcome:'불안하지만 당장의 월급을 지켰다.'},{text:'위로금을 받고 나온다',effects:{cash:[8000000,25000000],happy:3},outcome:'목돈과 함께 새 출발을 준비한다.'},{text:'이직 준비만 시작한다',effects:{cash:-500000,happy:2},outcome:'자격증과 포트폴리오를 준비했다.'}],'📦'),
 C('overtime','job','마감 직전 야근','예상 못 한 업무가 퇴근 직전에 쏟아졌습니다.',null,[{text:'끝까지 책임진다',effects:{cash:[200000,1000000],happy:-7},outcome:'수당과 신뢰를 얻었지만 몹시 지쳤다.'},{text:'우선순위를 협상한다',effects:{happy:3,charm:2},outcome:'중요한 일만 끝내고 퇴근했다.'},{text:'내일로 미룬다',effects:{happy:7},outcome:'오늘은 편했지만 내일이 걱정이다.'}],'🌙'),
 C('offer','job','경쟁사의 스카우트 제안','경쟁사가 연봉 인상과 함께 이직을 제안했습니다.',['office','dev','nurse','designer','sales','accountant','lawyer','researcher'],[{text:'조건을 받아 협상한다',effects:{cash:[1000000,4000000],happy:5},outcome:'현 직장에서 연봉과 역할을 다시 협상했다.'},{text:'과감히 옮긴다',effects:{cash:[2000000,7000000],happy:2},outcome:'불확실하지만 더 큰 기회를 택했다.'},{text:'안정성을 위해 거절한다',effects:{happy:4},outcome:'익숙한 환경과 팀을 선택했다.'}],'📨'),
 C('mistake','job','업무 실수 발견','아직 아무도 모르는 내 실수가 큰 문제로 번질 수 있습니다.',null,[{text:'즉시 보고하고 수습한다',effects:{cash:-300000,happy:-3},outcome:'질책은 받았지만 피해를 작게 막았다.'},{text:'혼자 밤새 해결한다',effects:{happy:-9},outcome:'문제는 해결했지만 심하게 지쳤다.'},{text:'모른 척한다',effects:{debt:[500000,6000000],happy:-8},outcome:'나중에 문제가 커져 비용과 신뢰를 잃었다.'}],'⚠️'),
 C('rider','job','폭우 배달 피크','폭우 때문에 배달 단가가 크게 올랐습니다.',['delivery'],[{text:'안전을 챙기며 몇 건만 한다',effects:{cash:[300000,900000],happy:-2},outcome:'무리하지 않고 추가 수입을 얻었다.'},{text:'밤새 최대한 달린다',effects:{cash:[1000000,3000000],debt:[0,3000000],happy:-10},outcome:'큰돈을 벌었지만 사고 위험도 감수했다.'},{text:'오늘은 쉰다',effects:{happy:8},outcome:'비 오는 창밖을 보며 푹 쉬었다.'}],'🌧️'),
 C('client','job','무리한 고객 요구','고객이 계약 범위를 넘는 수정을 계속 요구합니다.',['designer','dev','lawyer','accountant','realtor','sales'],[{text:'추가 비용을 청구한다',effects:{cash:[500000,3000000],happy:2},outcome:'노동의 값을 제대로 받았다.'},{text:'이번만 무료로 해준다',effects:{happy:-7,charm:2},outcome:'고객은 만족했지만 선례가 남았다.'},{text:'계약을 종료한다',effects:{cash:-500000,happy:8},outcome:'수입보다 정신 건강을 택했다.'}],'🧑‍💼'),
 C('viral','job','콘텐츠 역주행','예전에 만든 콘텐츠가 갑자기 추천을 타기 시작했습니다.',['youtuber','designer'],[{text:'후속 콘텐츠를 바로 만든다',effects:{cash:[2000000,10000000],happy:-5},outcome:'흐름을 놓치지 않고 수익을 키웠다.'},{text:'기존 콘텐츠를 다듬는다',effects:{cash:[500000,3000000],happy:3},outcome:'유행을 오래 가는 팬으로 바꿨다.'},{text:'평소처럼 쉰다',effects:{happy:8},outcome:'기회 대신 번아웃 방지를 택했다.'}],'🔥'),
 C('tax','life','연말정산 결과','기대하던 연말정산 결과가 나왔습니다.',null,[{text:'환급금을 비상금으로 둔다',effects:{cash:[300000,2500000],happy:3},outcome:'뜻밖의 돈을 안전하게 남겼다.'},{text:'갖고 싶던 물건을 산다',effects:{cash:[-1000000,500000],happy:12},outcome:'오래 고민하던 물건을 샀다.'},{text:'세액공제를 공부한다',effects:{cash:[200000,1500000],charm:2},outcome:'다음 해를 더 꼼꼼히 준비한다.'}],'🧾'),
 C('rent','life','월세 인상 통보','집주인이 다음 계약부터 월세를 올리겠다고 통보했습니다.',null,[{text:'조건을 협상한다',effects:{cash:-300000,happy:-2},outcome:'일부 인상만 받아들이기로 했다.'},{text:'더 저렴한 집으로 이사한다',effects:{cash:-1500000,happy:-4},outcome:'이사비는 들었지만 고정비를 낮췄다.'},{text:'그냥 받아들인다',effects:{cash:-800000,happy:-3},outcome:'이사 스트레스 대신 높은 월세를 감수했다.'}],'🏠'),
 C('family','life','가족의 건강검진','가족에게 정밀검사가 필요하다는 연락이 왔습니다.',null,[{text:'비용을 보태고 함께 간다',effects:{cash:-2000000,happy:7},outcome:'일찍 발견해 치료를 시작했다.'},{text:'일정을 알아봐준다',effects:{cash:-300000,happy:3},outcome:'실질적인 도움을 줄 수 있었다.'},{text:'바쁘다며 미룬다',effects:{happy:-10},outcome:'일에 집중했지만 죄책감이 남았다.'}],'🏥'),
 C('side','job','사이드 프로젝트 제안','퇴근 후 함께 작은 서비스를 만들자는 제안을 받았습니다.',['office','dev','designer','researcher','accountant'],[{text:'수익 배분을 정하고 참여한다',effects:{cash:[-500000,5000000],happy:-5,charm:5},outcome:'새로운 수입 가능성을 만들었다.'},{text:'주말 일부만 돕는다',effects:{cash:[0,1500000],happy:-2},outcome:'본업을 해치지 않는 선에서 경험을 쌓았다.'},{text:'거절하고 쉰다',effects:{happy:8},outcome:'기회 대신 휴식을 선택했다.'}],'🛠️'),
];
root.QT_CAREER_EVENTS=CAREER_EVENTS;
})(window);
