/* QuickTrade Life — 직업별·장 마감 월말 이벤트 */
(function(root){'use strict';
const C=(id,cat,title,desc,jobs,options,emoji='📋')=>({id:'career_'+id,cat,emoji,title,desc,jobs:jobs||null,cond:x=>!jobs||jobs.includes(x.job),options});
const CAREER_EVENTS=[
 C('bonus','job','예상 밖의 성과급','팀 실적이 좋아 특별 성과급 대상이 됐습니다.',null,[{text:'전액 투자한다',effects:{cash:[1000000,5000000],happy:2},outcome:'보너스를 투자 계좌로 옮겼다.'},{text:'절반은 저축하고 절반은 쓴다',effects:{cash:[500000,2500000],happy:8},outcome:'미래와 현재를 함께 챙겼다.'},{text:'동료들에게 한턱낸다',effects:{cash:[-500000,500000],happy:12,charm:3},outcome:'통장은 가벼워졌지만 평판은 좋아졌다.'}],'💰'),
 C('layoff','job','희망퇴직 공고','회사가 큰 위로금을 걸고 희망퇴직 신청을 받습니다.',['office','dev','designer','sales','researcher','factory'],[{text:'남아서 버틴다',effects:{happy:-4},outcome:'불안하지만 당장의 월급을 지켰다.'},{text:'위로금을 받고 나온다',effects:{cash:[8000000,25000000],happy:3},outcome:'목돈과 함께 새 출발을 준비한다.'},{text:'이직 준비만 시작한다',effects:{cash:-500000,happy:2},outcome:'자격증과 포트폴리오를 준비했다.'}],'📦'),
 C('overtime','job','마감 직전 야근','예상 못 한 업무가 퇴근 직전에 쏟아졌습니다.',null,[{text:'끝까지 책임진다',effects:{cash:[200000,1000000],happy:-7},outcome:'수당과 신뢰를 얻었지만 몹시 지쳤다.'},{text:'우선순위를 협상한다',effects:{happy:3,charm:2},outcome:'중요한 일만 끝내고 퇴근했다.'},{text:'내일로 미룬다',effects:{happy:7},outcome:'오늘은 편했지만 내일이 걱정이다.'}],'🌙'),
 C('offer','job','경쟁사의 스카우트 제안','경쟁사가 연봉 인상과 함께 이직을 제안했습니다.',['office','dev','nurse','designer','sales','accountant','lawyer','researcher'],[{text:'조건을 받아 협상한다',effects:{cash:[1000000,4000000],happy:5},outcome:'현 직장에서 연봉과 역할을 다시 협상했다.'},{text:'과감히 옮긴다',effects:{cash:[2000000,7000000],happy:2},outcome:'불확실하지만 더 큰 기회를 택했다.'},{text:'안정성을 위해 거절한다',effects:{happy:4},outcome:'익숙한 환경과 팀을 선택했다.'}],'📨'),
 C('mistake','job','업무 실수 발견','아직 아무도 모르는 내 실수가 큰 문제로 번질 수 있습니다.',null,[{text:'즉시 보고하고 수습한다',effects:{cash:-300000,happy:-3},outcome:'질책은 받았지만 피해를 작게 막았다.'},{text:'혼자 밤새 해결한다',effects:{happy:-9},outcome:'문제는 해결했지만 심하게 지쳤다.'},{text:'모른 척한다',effects:{debt:[500000,6000000],happy:-8},outcome:'나중에 문제가 커져 비용과 신뢰를 잃었다.'}],'⚠️'),
 C('rider','job','폭우 배달 피크','폭우 때문에 배달 단가가 크게 올랐습니다.',['delivery'],[{text:'안전을 챙기며 몇 건만 한다',effects:{cash:[300000,900000],happy:-2},outcome:'무리하지 않고 추가 수입을 얻었다.'},{text:'밤새 최대한 달린다',effects:{cash:[1000000,3000000],debt:[0,3000000],happy:-10},outcome:'큰돈을 벌었지만 사고 위험도 감수했다.'},{text:'오늘은 쉰다',effects:{happy:8},outcome:'비 오는 창밖을 보며 푹 쉬었다.'}],'🌧️'),
 C('client','job','무리한 고객 요구','고객이 계약 범위를 넘는 수정을 계속 요구합니다.',['designer','dev','lawyer','accountant','realtor','sales'],[{text:'추가 비용을 청구한다',effects:{cash:[500000,3000000],happy:2},outcome:'노동의 값을 제대로 받았다.'},{text:'이번만 무료로 해준다',effects:{happy:-7,charm:2},outcome:'고객은 만족했지만 선례가 남았다.'},{text:'계약을 종료한다',effects:{cash:-500000,happy:8},outcome:'수입보다 정신 건강을 택했다.'}],'🧑‍💼'),
 C('viral','job','콘텐츠 역주행','예전에 만든 콘텐츠가 갑자기 추천을 타기 시작했습니다.',['youtuber','designer'],[{text:'후속 콘텐츠를 바로 만든다',effects:{cash:[2000000,10000000],happy:-5},outcome:'흐름을 놓치지 않고 수익을 키웠다.'},{text:'기존 콘텐츠를 다듬는다',effects:{cash:[500000,3000000],happy:3},outcome:'유행을 오래 가는 팬으로 바꿨다.'},{text:'평소처럼 쉰다',effects:{happy:8},outcome:'기회 대신 번아웃 방지를 택했다.'}],'🔥'),
 C('tax','life','연말정산 결과','기대하던 연말정산 결과가 나왔습니다.',null,[{text:'환급금을 비상금으로 둔다',effects:{cash:[300000,2500000],happy:3},outcome:'뜻밖의 돈을 안전하게 남겼다.'},{text:'갖고 싶던 물건을 산다',effects:{cash:[-1000000,500000],happy:12},outcome:'오래 고민하던 물건을 샀다.'},{text:'세액공제를 공부한다',effects:{cash:[200000,1500000],charm:2},outcome:'다음 해를 더 꼼꼼히 준비한다.'}],'🧾'),
 C('rent','life','월세 인상 통보','집주인이 다음 계약부터 월세를 올리겠다고 통보했습니다.',null,[{text:'조건을 협상한다',effects:{cash:-300000,happy:-2},outcome:'일부 인상만 받아들이기로 했다.'},{text:'더 저렴한 집으로 이사한다',effects:{cash:-1500000,happy:-4},outcome:'이사비는 들었지만 고정비를 낮췄다.'},{text:'그냥 받아들인다',effects:{cash:-800000,happy:-3},outcome:'이사 스트레스 대신 높은 월세를 감수했다.'}],'🏠'),
 C('family','life','가족의 건강검진','가족에게 정밀검사가 필요하다는 연락이 왔습니다.',null,[{text:'비용을 보태고 함께 간다',effects:{cash:-2000000,happy:7},outcome:'일찍 발견해 치료를 시작했다.'},{text:'일정을 알아봐준다',effects:{cash:-300000,happy:3},outcome:'실질적인 도움을 줄 수 있었다.'},{text:'바쁘다며 미룬다',effects:{happy:-10},outcome:'일에 집중했지만 죄책감이 남았다.'}],'🏥'),
 C('side','job','사이드 프로젝트 제안','퇴근 후 함께 작은 서비스를 만들자는 제안을 받았습니다.',['office','dev','designer','researcher','accountant'],[{text:'수익 배분을 정하고 참여한다',effects:{cash:[-500000,5000000],happy:-5,charm:5},outcome:'새로운 수입 가능성을 만들었다.'},{text:'주말 일부만 돕는다',effects:{cash:[0,1500000],happy:-2},outcome:'본업을 해치지 않는 선에서 경험을 쌓았다.'},{text:'거절하고 쉰다',effects:{happy:8},outcome:'기회 대신 휴식을 선택했다.'}],'🛠️'),
 C('parttime_night','job','심야 대타 요청','점장이 갑자기 심야 근무를 대신해 달라고 부탁했습니다.',['parttime'],[{text:'추가수당을 받고 나간다',effects:{cash:[300000,800000],happy:-6},outcome:'피곤했지만 이번 달 수입을 제법 늘렸다.'},{text:'다음 근무 교환을 조건으로 돕는다',effects:{cash:[100000,400000],happy:-2,charm:2},outcome:'서로 부담을 나누는 조건으로 합의했다.'},{text:'이미 약속이 있다며 거절한다',effects:{happy:5},outcome:'수당 대신 내 시간을 지켰다.'}],'🌙'),
 C('office_pitch','job','임원 앞 긴급 발표','담당자가 빠져 중요한 발표를 대신 맡게 됐습니다.',['office'],[{text:'밤새 준비해 발표한다',effects:{cash:[500000,2500000],happy:-7,charm:3},outcome:'성과급과 임원들의 눈도장을 함께 얻었다.'},{text:'팀원들과 역할을 나눈다',effects:{cash:[200000,1200000],happy:2},outcome:'혼자 영웅이 되진 않았지만 발표를 안정적으로 마쳤다.'},{text:'경험 부족을 이유로 피한다',effects:{happy:4,charm:-2},outcome:'큰 실수는 피했지만 다음 기회도 멀어졌다.'}],'📊'),
 C('civil_emergency','job','비상근무 소집','지역 재난 대응을 위한 주말 비상근무가 잡혔습니다.',['civil'],[{text:'현장 지원을 자원한다',effects:{cash:[200000,900000],happy:-6,charm:4},outcome:'힘들었지만 주민들의 감사와 수당을 받았다.'},{text:'행정 지원을 맡는다',effects:{cash:[100000,500000],happy:-2},outcome:'뒤에서 차분히 현장을 지원했다.'},{text:'개인 사정으로 빠진다',effects:{happy:5,charm:-1},outcome:'휴식은 지켰지만 동료들에게 일이 몰렸다.'}],'🚨'),
 C('dev_security','job','보안 취약점 발견','출시 직전 서비스에서 치명적인 취약점을 발견했습니다.',['dev'],[{text:'공개를 미루고 전면 수정한다',effects:{cash:[1000000,7000000],happy:-10},outcome:'출시는 늦었지만 대형 사고를 막아 특별 보상을 받았다.'},{text:'핵심 부분만 긴급 패치한다',effects:{cash:[300000,2500000],happy:-4},outcome:'일정과 안전 사이에서 현실적인 타협을 했다.'},{text:'들키지 않길 바라며 출시한다',effects:{cash:[-8000000,3000000],debt:[0,8000000],happy:-12},outcome:'운이 좋으면 넘어가지만 터지면 손해배상까지 이어진다.'}],'🔐'),
 C('doctor_emergency','job','고난도 응급수술','다른 병원에서 거절한 고난도 응급 환자가 이송됐습니다.',['doctor'],[{text:'전문팀을 꾸려 수술한다',effects:{cash:[5000000,18000000],happy:-9,charm:5},outcome:'큰 책임을 감수했고 성공 보상도 컸다.'},{text:'상급병원과 공동 대응한다',effects:{cash:[1500000,7000000],happy:-3},outcome:'수익은 나눴지만 위험도 함께 줄였다.'},{text:'안전하게 전원시킨다',effects:{happy:3,charm:-1},outcome:'무리한 선택을 피했지만 아쉬움이 남았다.'}],'🫀'),
 C('youtuber_sponsor','job','대형 광고 계약','한 달 수입을 바꿀 대형 광고 제안이 들어왔지만 제품 평판이 애매합니다.',['youtuber'],[{text:'직접 검증 후 조건부로 받는다',effects:{cash:[3000000,15000000],happy:-4,charm:3},outcome:'검증 과정을 공개해 수익과 신뢰를 함께 챙겼다.'},{text:'광고료만 보고 바로 계약한다',effects:{cash:[5000000,22000000],debt:[0,10000000],happy:-8},outcome:'큰돈을 벌었지만 논란이 터지면 환불과 배상이 뒤따른다.'},{text:'구독자 신뢰를 위해 거절한다',effects:{happy:7,charm:5},outcome:'당장 돈은 놓쳤지만 팬들의 신뢰는 깊어졌다.'}],'📹'),
 C('ceo_contract','job','회사를 건 대형 계약','매출을 몇 배로 키울 계약이지만 선투자와 납기 위험이 큽니다.',['ceo'],[{text:'회사 자금을 집중 투입한다',effects:{cash:[-10000000,35000000],debt:[0,12000000],happy:-9},outcome:'성공하면 대박, 실패하면 운영자금 압박이 남는다.'},{text:'규모를 줄여 단계 계약한다',effects:{cash:[2000000,12000000],happy:-2},outcome:'폭발적인 성장은 포기하고 생존 가능한 계약을 만들었다.'},{text:'조건이 나빠 거절한다',effects:{happy:5},outcome:'기회를 놓쳤지만 회사의 현금흐름을 지켰다.'}],'🏗️'),
 C('delivery_bonus','job','플랫폼 연속운행 보너스','이번 주 목표 건수를 채우면 큰 보너스를 받을 수 있습니다.',['delivery'],[{text:'안전 한도를 정하고 도전한다',effects:{cash:[600000,1800000],happy:-4},outcome:'무리하지 않는 선에서 보너스를 챙겼다.'},{text:'잠을 줄여 끝까지 채운다',effects:{cash:[1500000,4000000],debt:[0,2500000],happy:-12},outcome:'수입은 컸지만 사고와 수리비 위험도 커졌다.'},{text:'평소 페이스를 유지한다',effects:{cash:[200000,700000],happy:4},outcome:'보너스보다 다음 달에도 일할 체력을 남겼다.'}],'🛵'),
 C('factory_quality','job','불량률 개선 제안','생산라인 불량 원인을 찾아 개선안을 제안할 기회가 생겼습니다.',['factory'],[{text:'직접 시험라인을 맡는다',effects:{cash:[600000,3000000],happy:-5,charm:3},outcome:'성과급을 받았고 현장에서도 실력을 인정받았다.'},{text:'안전팀과 함께 천천히 개선한다',effects:{cash:[300000,1400000],happy:1},outcome:'속도는 느렸지만 사고 없이 불량률을 낮췄다.'},{text:'괜히 책임지지 않는다',effects:{happy:4},outcome:'추가 업무는 피했지만 개선 기회도 지나갔다.'}],'🏭'),
 C('teacher_program','job','방과후 프로그램 제안','학생들을 위한 새 방과후 프로그램 책임자를 맡아 달라는 요청을 받았습니다.',['teacher'],[{text:'직접 프로그램을 만든다',effects:{cash:[300000,1500000],happy:-5,charm:5},outcome:'업무는 늘었지만 학생과 학부모의 반응이 좋았다.'},{text:'동료와 공동 운영한다',effects:{cash:[100000,700000],happy:2},outcome:'부담을 나누며 프로그램을 안정적으로 시작했다.'},{text:'본업에 집중한다며 거절한다',effects:{happy:5},outcome:'추가 수당은 없지만 수업 준비 시간을 지켰다.'}],'🏫'),
 C('nurse_shift','job','중환자실 긴급 지원','인력 공백으로 중환자실 긴급 지원 요청이 왔습니다.',['nurse'],[{text:'추가 근무를 맡는다',effects:{cash:[800000,3000000],happy:-9,charm:4},outcome:'고강도 근무를 버티고 특별수당을 받았다.'},{text:'절반 교대만 맡는다',effects:{cash:[300000,1400000],happy:-3},outcome:'동료를 돕되 허리와 체력도 지켰다.'},{text:'몸 상태를 이유로 거절한다',effects:{happy:6},outcome:'수당보다 건강을 우선했다.'}],'🩺'),
 C('designer_pitch','job','브랜드 리뉴얼 경쟁 PT','대형 브랜드 리뉴얼을 따내기 위한 경쟁 프레젠테이션이 열렸습니다.',['designer'],[{text:'외주까지 써서 승부한다',effects:{cash:[-2000000,10000000],happy:-7,charm:5},outcome:'투자한 만큼 결과의 폭도 커졌다.'},{text:'작은 핵심 시안으로 설득한다',effects:{cash:[500000,4000000],happy:-2},outcome:'과한 비용 없이 방향성을 인정받았다.'},{text:'일정을 이유로 포기한다',effects:{happy:6},outcome:'대형 계약은 놓쳤지만 기존 마감을 지켰다.'}],'🎨'),
 C('sales_account','job','대형 고객 최종 협상','분기 실적을 뒤집을 대형 고객과 마지막 조건 협상이 남았습니다.',['sales'],[{text:'마진을 지키며 끝까지 협상한다',effects:{cash:[2000000,12000000],happy:-6,charm:4},outcome:'쉽지 않았지만 큰 인센티브를 확보했다.'},{text:'조건을 양보해 계약부터 잡는다',effects:{cash:[800000,5000000],happy:-2},outcome:'수익은 줄었지만 안정적인 거래처를 얻었다.'},{text:'무리한 요구라 계약을 접는다',effects:{happy:6,charm:2},outcome:'실적보다 장기적인 신뢰를 택했다.'}],'🤝'),
 C('accountant_audit','job','긴급 회계감사','대형 고객의 긴급 감사 업무를 짧은 기한 안에 끝내야 합니다.',['accountant'],[{text:'전담팀을 꾸려 수임한다',effects:{cash:[3000000,14000000],happy:-9},outcome:'강도 높은 업무만큼 큰 수임료를 받았다.'},{text:'범위를 줄여 제한적으로 맡는다',effects:{cash:[1200000,6000000],happy:-3},outcome:'책임 범위를 명확히 해 위험을 낮췄다.'},{text:'품질을 지키기 위해 거절한다',effects:{happy:5,charm:2},outcome:'수임료보다 감사 품질과 평판을 지켰다.'}],'🧾'),
 C('lawyer_case','job','사회적 이목이 쏠린 사건','승소하면 이름을 알릴 수 있지만 패소 위험도 큰 사건이 들어왔습니다.',['lawyer'],[{text:'성과보수 조건으로 맡는다',effects:{cash:[-3000000,18000000],debt:[0,5000000],happy:-8,charm:5},outcome:'결과에 따라 명성과 수입이 크게 갈린다.'},{text:'고정 수임료로 공동 변론한다',effects:{cash:[2000000,8000000],happy:-3},outcome:'위험과 보상을 동료와 나눴다.'},{text:'현재 사건에 집중한다며 거절한다',effects:{happy:5},outcome:'화제성보다 기존 의뢰인의 신뢰를 지켰다.'}],'⚖️'),
 C('research_patent','job','연구 성과 특허 제안','오랫동안 진행한 연구에서 사업화 가능한 결과가 나왔습니다.',['researcher'],[{text:'개인 자금도 넣어 사업화한다',effects:{cash:[-3000000,15000000],happy:-5,charm:4},outcome:'실패 위험을 감수하고 연구를 시장으로 가져갔다.'},{text:'기관에 기술이전한다',effects:{cash:[1000000,6000000],happy:3},outcome:'큰 대박 대신 안정적인 기술료를 택했다.'},{text:'논문 발표에 집중한다',effects:{cash:[0,1500000],happy:6,charm:2},outcome:'돈보다 연구 성과와 이름을 남겼다.'}],'🔬'),
 C('realtor_listing','job','고가 매물 전속 계약','성사되면 큰 수수료지만 광고비와 법적 검토가 필요한 매물입니다.',['realtor'],[{text:'광고비를 들여 전면 홍보한다',effects:{cash:[-4000000,18000000],debt:[0,4000000],happy:-6},outcome:'거래 성사 여부에 따라 수익이 크게 갈렸다.'},{text:'공동중개로 위험을 나눈다',effects:{cash:[1000000,7000000],happy:-2},outcome:'수수료는 나눴지만 안전하게 거래를 진행했다.'},{text:'권리관계가 복잡해 거절한다',effects:{happy:5,charm:2},outcome:'큰 수수료보다 중개사고 위험을 피했다.'}],'🏠'),
];

/* =========================================================================
 *  확장 — 신규 직업 전용 이벤트 + 리스크 큰 상황들
 * ========================================================================= */
CAREER_EVENTS.push(
 /* ---- 신규 직업 전용 ---- */
 C('trader_margin','job','증거금 부족 경고','전업 투자 계좌에 마진콜이 임박했습니다. 반대매매까지 시간이 없습니다.',['trader'],[{text:'손절하고 현금을 확보한다',effects:{cash:[-6000000,-1000000],happy:-6},outcome:'아팠지만 계좌가 통째로 날아가는 건 막았다.'},{text:'추가 증거금을 넣어 버틴다',effects:{cash:[-12000000,25000000],debt:[0,10000000],happy:-10},outcome:'반등하면 대박, 아니면 빚까지 남는 도박이었다.'},{text:'포지션 절반만 정리한다',effects:{cash:[-3000000,4000000],happy:-3},outcome:'위험과 기대를 반씩 안고 갔다.'}],'📉'),
 C('trader_tip','job','확실하다는 정보','지인이 "이번엔 진짜"라며 급등 예정 종목을 귀띔합니다.',['trader'],[{text:'직접 검증하고 소액만 넣는다',effects:{cash:[-1000000,5000000],happy:1},outcome:'남의 말보다 내 판단을 우선했다.'},{text:'전 재산을 태워 몰빵한다',effects:{cash:[-20000000,45000000],debt:[0,15000000],happy:-8},outcome:'인생을 건 베팅, 결과는 하늘에 맡겼다.'},{text:'무시하고 원칙을 지킨다',effects:{happy:4},outcome:'귀는 닫고 계획대로 갔다.'}],'🤫'),
 C('firefighter_rescue','job','건물 붕괴 직전 구조','붕괴 위험이 있는 건물 안에 요구조자가 남아 있습니다.',['firefighter'],[{text:'진입해 끝까지 구조한다',effects:{cash:[500000,3000000],debt:[0,6000000],happy:-6,charm:8},outcome:'생명을 구했지만 부상 위험을 무릅썼다.'},{text:'안전 절차를 지키며 접근한다',effects:{cash:[200000,1200000],happy:-2,charm:4},outcome:'원칙대로 움직여 팀 전체를 지켰다.'},{text:'지원을 기다린다',effects:{happy:-4,charm:-2},outcome:'안전했지만 구조가 늦어 마음이 무거웠다.'}],'🔥'),
 C('police_bribe','job','수사 무마 청탁','수사 대상이 거액을 건네며 사건을 덮어달라고 합니다.',['police'],[{text:'거절하고 뇌물 시도를 기록한다',effects:{happy:4,charm:5},outcome:'유혹을 이겨내고 신뢰를 지켰다.'},{text:'못 이기는 척 받는다',effects:{cash:[10000000,40000000],debt:[0,20000000],happy:-12},outcome:'큰돈이 들어왔지만 언젠가 목을 조일 약점이 됐다.'},{text:'상부에 보고한다',effects:{happy:2,charm:3},outcome:'절차대로 처리해 뒤탈을 없앴다.'}],'💵'),
 C('pilot_medical','job','정기 신체검사','파일럿 자격 유지를 위한 정기 신체검사 시즌입니다.',['pilot'],[{text:'미리 관리하고 검사를 받는다',effects:{cash:-800000,happy:3},outcome:'꾸준한 관리로 무사히 통과했다.'},{text:'바빠서 대충 준비한다',effects:{cash:[-8000000,0],happy:-8},outcome:'하마터면 정직될 뻔했다. 다음엔 미리 챙기기로 했다.'},{text:'휴가를 내고 컨디션을 끌어올린다',effects:{cash:-2000000,happy:6},outcome:'몸도 마음도 재정비하고 복귀했다.'}],'🩻'),
 C('progamer_prime','job','전성기의 갈림길','팀 재계약과 은퇴 후 진로를 함께 고민할 시기가 왔습니다.',['progamer'],[{text:'조건을 높여 재계약한다',effects:{cash:[3000000,12000000],happy:-3},outcome:'전성기를 조금 더 이어가기로 했다.'},{text:'스트리머로 전환을 준비한다',effects:{cash:[-1000000,6000000],happy:4,charm:4},outcome:'선수 이후의 삶을 미리 설계했다.'},{text:'무리하게 대회에 매달린다',effects:{cash:[0,4000000],happy:-9},outcome:'성적 압박에 몸과 마음이 함께 상했다.'}],'🏆'),
 C('webtoon_deal','job','플랫폼 정식 연재 제안','대형 플랫폼에서 정식 연재를 제안했지만 마감 강도가 살인적입니다.',['webtoon'],[{text:'어시스턴트를 고용해 도전한다',effects:{cash:[-2000000,14000000],happy:-8},outcome:'투자한 만큼 연재 성공 가능성도 커졌다.'},{text:'격주 연재로 조건을 조정한다',effects:{cash:[500000,6000000],happy:-2},outcome:'속도를 낮춰 지속 가능성을 확보했다.'},{text:'건강을 위해 거절한다',effects:{happy:6},outcome:'큰 기회 대신 번아웃을 피했다.'}],'🖌️'),
 C('chef_restaurant','job','내 가게 개업 제안','투자자가 함께 레스토랑을 열자고 제안합니다.',['chef'],[{text:'대출까지 받아 크게 연다',effects:{cash:[-8000000,30000000],debt:[0,15000000],happy:-6},outcome:'인생을 건 개업, 성패는 손님이 정한다.'},{text:'작은 가게부터 시작한다',effects:{cash:[-3000000,10000000],happy:2},outcome:'무리하지 않는 규모로 첫발을 뗐다.'},{text:'주방장으로 남는다',effects:{happy:4},outcome:'리스크 대신 안정적인 월급을 택했다.'}],'🍽️'),
 C('construction_safety','job','현장 안전 점검','오늘 작업 현장의 안전 설비가 미흡해 보입니다.',['construction','factory'],[{text:'작업을 멈추고 개선을 요구한다',effects:{cash:[-500000,0],happy:3,charm:3},outcome:'일당은 줄었지만 사고를 예방했다.'},{text:'조심하며 그대로 진행한다',effects:{cash:[500000,2000000],debt:[0,10000000],happy:-4},outcome:'돈은 벌었지만 위험을 안고 일했다.'},{text:'위험 구역만 피해 일한다',effects:{cash:[300000,1200000],happy:0},outcome:'현실적인 선에서 타협했다.'}],'🦺'),
 C('fisher_storm','job','출항 앞둔 기상특보','만선이 예상되지만 먼바다에 폭풍 경보가 내렸습니다.',['fisher'],[{text:'경보를 무시하고 출항한다',effects:{cash:[3000000,12000000],debt:[0,12000000],happy:-8},outcome:'큰 조업이었지만 목숨을 걸었다.'},{text:'날이 풀릴 때까지 기다린다',effects:{cash:[-1000000,500000],happy:2},outcome:'수입은 놓쳤지만 배와 선원을 지켰다.'},{text:'연안에서 소규모로 조업한다',effects:{cash:[500000,2500000],happy:0},outcome:'욕심을 줄여 안전하게 벌었다.'}],'🌊'),
 C('stuntman_bigshot','job','위험한 특수 촬영','A급 영화의 고난도 액션 대역 제안이 들어왔습니다.',['stuntman'],[{text:'철저히 준비하고 도전한다',effects:{cash:[3000000,12000000],debt:[0,8000000],happy:-4,charm:6},outcome:'경력을 바꿀 장면을 남겼지만 위험도 컸다.'},{text:'와이어·CG 보조를 조건으로 건다',effects:{cash:[1500000,6000000],happy:1},outcome:'안전장치를 확보하고 촬영했다.'},{text:'너무 위험해 고사한다',effects:{happy:5},outcome:'몸을 지키는 쪽을 택했다.'}],'🎬'),

 /* ---- 적성/커리어 일반 ---- */
 C('aptitude_gap','job','적성에 안 맞는 업무','지금 하는 일이 도무지 손에 붙지 않아 실수가 잦습니다.',null,[{text:'약점을 인정하고 교육을 받는다',effects:{cash:-1000000,happy:2},outcome:'느리지만 조금씩 나아지고 있다.'},{text:'강점을 살릴 업무로 재배치를 요청한다',effects:{happy:6,charm:2},outcome:'잘하는 일로 옮기니 성과가 붙기 시작했다.'},{text:'버티며 그냥 참는다',effects:{happy:-8},outcome:'스트레스만 쌓이고 사고 위험이 커졌다.'}],'🧭'),
 C('headhunt','job','헤드헌터의 연락','당신의 경력에 관심 있다는 헤드헌터가 커피챗을 제안합니다.',null,[{text:'시장 가치를 확인하고 협상 카드로 쓴다',effects:{cash:[500000,3000000],happy:4,charm:3},outcome:'몸값을 확인해 현 직장과 다시 협상했다.'},{text:'진지하게 이직을 검토한다',effects:{happy:3},outcome:'더 나은 기회의 문을 열어뒀다.'},{text:'지금이 좋다며 정중히 거절한다',effects:{happy:2},outcome:'익숙한 자리를 지켰다.'}],'🕵️'),
 C('burnout_leave','job','번아웃 신호','아침에 눈을 떠도 출근할 힘이 나지 않는 날이 이어집니다.',null,[{text:'유급 휴직을 신청한다',effects:{cash:[-2000000,0],happy:14},outcome:'잠시 멈추자 다시 걸을 힘이 생겼다.'},{text:'업무를 줄이고 상담을 받는다',effects:{cash:-500000,happy:9},outcome:'속도를 늦추니 숨이 트였다.'},{text:'약으로 버티며 계속 일한다',effects:{cash:-300000,happy:-6},outcome:'당장은 버텼지만 더 크게 무너질 위험이 남았다.'}],'🕯️'),
 C('reskill','job','사내 재교육 기회','회사가 유망 직무로의 전환 교육 대상자를 모집합니다.',null,[{text:'적극 지원해 새 기술을 배운다',effects:{cash:-800000,happy:4,charm:3},outcome:'미래를 대비한 무기를 하나 더 얻었다.'},{text:'업무와 병행해 조금씩 배운다',effects:{happy:1},outcome:'느리지만 꾸준히 역량을 넓혔다.'},{text:'지금 일에 집중한다',effects:{happy:2},outcome:'현재 성과에 몰두하기로 했다.'}],'📚'),
 C('coworker_credit','job','가로채인 공','내가 주도한 프로젝트의 공을 상사가 가로챘습니다.',null,[{text:'근거를 정리해 조용히 바로잡는다',effects:{happy:3,charm:3},outcome:'감정 없이 사실로 인정받았다.'},{text:'회의에서 정면으로 문제삼는다',effects:{happy:-4,charm:1},outcome:'진실은 드러났지만 관계가 껄끄러워졌다.'},{text:'다음을 노리고 넘어간다',effects:{happy:-6},outcome:'참았지만 같은 일이 반복될 것 같다.'}],'😤'),
 C('salary_nego','job','연봉 협상 시즌','성과를 근거로 연봉 인상을 요구할 때가 왔습니다.',null,[{text:'구체적 성과로 강하게 요구한다',effects:{cash:[1000000,5000000],happy:5},outcome:'준비한 자료가 통해 인상을 받아냈다.'},{text:'적당한 선에서 합의한다',effects:{cash:[300000,1800000],happy:3},outcome:'무리 없이 조금 올렸다.'},{text:'분위기를 보다 다음을 기약한다',effects:{happy:-3},outcome:'기회를 미뤘고 아쉬움이 남았다.'}],'💹'),
 C('startup_join','job','초기 스타트업 합류 제안','지분을 받고 초기 스타트업에 합류하라는 제안을 받았습니다.',null,[{text:'연봉을 낮추고 지분을 받는다',effects:{cash:[-3000000,20000000],debt:[0,3000000],happy:-3,charm:4},outcome:'대박 아니면 쪽박, 큰 베팅을 했다.'},{text:'자문으로만 참여한다',effects:{cash:[300000,3000000],happy:2},outcome:'위험은 줄이고 기회는 조금 잡았다.'},{text:'안정성을 위해 거절한다',effects:{happy:3},outcome:'현실적인 선택을 했다.'}],'🚀'),
 C('injury_comp','job','산재 처리 갈등','업무 중 다쳤는데 회사가 산재 처리를 꺼립니다.',['construction','factory','delivery','firefighter','fisher','stuntman','nurse'],[{text:'정식으로 산재를 신청한다',effects:{cash:[500000,5000000],happy:2,charm:2},outcome:'정당한 보상과 치료를 받았다.'},{text:'합의금을 받고 조용히 마무리한다',effects:{cash:[1000000,4000000],happy:-2},outcome:'당장 목돈은 받았지만 후유증이 걱정이다.'},{text:'참고 그냥 복귀한다',effects:{debt:[0,5000000],happy:-8},outcome:'몸을 혹사한 대가가 나중에 돌아왔다.'}],'🩹'),
 C('mentor_offer','job','후배 멘토링 요청','회사가 신입 멘토를 맡아달라고 요청합니다.',null,[{text:'기꺼이 맡아 후배를 키운다',effects:{cash:[100000,800000],happy:5,charm:4},outcome:'가르치며 나도 함께 성장했다.'},{text:'가볍게 조언만 해준다',effects:{happy:2,charm:1},outcome:'부담 없이 좋은 관계를 맺었다.'},{text:'내 일이 바쁘다며 사양한다',effects:{happy:1},outcome:'내 업무에 집중했다.'}],'🧑‍🏫')
);
root.QT_CAREER_EVENTS=CAREER_EVENTS;
})(window);
