/* QuickTrade Life — 자녀 성격·성장 선택 이벤트 */
(function(root){'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a[Math.floor(Math.random()*a.length)];
const EVENTS=[
 {stages:['영유아'],emoji:'🧸',title:'낯선 사람을 무서워해요',desc:'어린이집 적응 기간, {name}이 매일 아침 울음을 터뜨립니다.',options:[['휴가를 내고 천천히 적응시킨다',{cash:-1200000,bond:12,happy:8,health:2},'안정감을 되찾고 부모를 더 신뢰하게 됐습니다.'],['전문 적응 프로그램을 등록한다',{cash:-600000,education:5,happy:4},'전문가의 도움으로 새로운 환경에 익숙해졌습니다.'],['시간이 해결하게 둔다',{bond:-8,happy:-10},'적응은 했지만 한동안 서운함이 남았습니다.']]},
 {stages:['유치원'],emoji:'🎨',title:'벽지가 도화지가 됐다',desc:'{name}이 거실 벽을 온통 그림으로 채웠습니다.',options:[['재능을 칭찬하고 미술학원에 보낸다',{cash:-900000,education:9,bond:7,talent:'예술'},'혼나는 대신 가능성을 발견했습니다.'],['함께 벽을 닦으며 규칙을 알려준다',{bond:10,happy:3},'책임과 규칙을 자연스럽게 배웠습니다.'],['크게 혼낸다',{bond:-10,happy:-12},'낙서는 멈췄지만 표현도 조심스러워졌습니다.']]},
 {stages:['초등학생'],emoji:'📚',title:'첫 성적표',desc:'{name}이 기대보다 낮은 성적표를 숨기고 있었습니다.',options:[['함께 공부법을 찾아본다',{cash:-400000,education:8,bond:9},'실수보다 개선 방법에 집중했습니다.'],['고액 과외를 붙인다',{cash:-1800000,education:15,happy:-5},'성적은 빠르게 올랐지만 부담도 커졌습니다.'],['성적보다 잘한 일을 묻는다',{bond:12,happy:10,education:2},'자존감과 가족 유대가 깊어졌습니다.']]},
 {stages:['초등학생'],traits:['social'],emoji:'🤝',title:'반장 선거에 나가고 싶어요',desc:'사교적인 {name}이 반장 선거 공약을 고민합니다.',options:[['발표 연습을 도와준다',{cash:-200000,bond:8,education:7,talent:'관계'},'사람 앞에서 말하는 자신감을 얻었습니다.'],['스스로 준비하게 한다',{education:4,happy:5},'결과와 관계없이 독립심을 배웠습니다.'],['괜히 튀지 말라고 말린다',{bond:-7,happy:-9},'도전해 보지 못한 아쉬움이 남았습니다.']]},
 {stages:['중학생'],emoji:'📱',title:'스마트폰과 밤샘',desc:'{name}이 새벽까지 휴대폰을 보느라 학교에서 졸았습니다.',options:[['가족이 함께 사용 규칙을 만든다',{bond:9,education:5,happy:2},'납득할 만한 규칙이라 스스로 지키기 시작했습니다.'],['휴대폰을 압수한다',{bond:-10,education:4,happy:-12},'수면은 회복됐지만 대화가 줄었습니다.'],['취미 활동으로 관심을 돌린다',{cash:-700000,bond:6,happy:9,health:4},'생활 리듬과 새로운 관심사를 찾았습니다.']]},
 {stages:['중학생'],traits:['rebellious'],emoji:'⚡',title:'무단결석 연락',desc:'자유로운 {name}이 친구들과 학교를 빠졌다는 연락이 왔습니다.',options:[['이유부터 차분히 듣는다',{bond:12,happy:4,education:2},'학교에서 겪던 갈등을 처음 털어놓았습니다.'],['상담센터와 학교를 함께 찾는다',{cash:-500000,bond:7,education:7,health:3},'문제를 숨기지 않고 해결하는 법을 배웠습니다.'],['용돈을 끊고 엄벌한다',{bond:-16,happy:-15,education:-3},'당장은 조용해졌지만 반항심이 깊어졌습니다.']]},
 {stages:['고등학생'],emoji:'📝',title:'진로 선택의 밤',desc:'{name}이 안정적인 전공과 진짜 좋아하는 분야 사이에서 고민합니다.',options:[['적성검사와 체험을 지원한다',{cash:-1200000,education:12,bond:10},'근거를 갖고 스스로 진로를 정했습니다.'],['취업이 잘되는 전공을 권한다',{education:10,happy:-8,bond:-4,talent:'안정'},'현실적인 길을 골랐지만 미련이 남았습니다.'],['좋아하는 길을 전폭 지지한다',{cash:-600000,happy:13,bond:12,talent:'창의'},'불확실성까지 감수할 용기를 얻었습니다.']]},
 {stages:['고등학생'],traits:['driven'],emoji:'🔥',title:'창업 동아리 투자 제안',desc:'야망 있는 {name}이 학교 창업대회 준비금이 필요하다고 합니다.',options:[['작은 시드와 회계 원칙을 준다',{cash:-2000000,education:14,bond:8,talent:'사업'},'돈과 책임을 함께 배운 첫 사업이 됐습니다.'],['계획서를 통과하면 지원한다',{cash:-800000,education:11,happy:4},'계획을 숫자로 검증하는 습관을 얻었습니다.'],['학생은 공부가 우선이라 거절한다',{education:3,bond:-8,happy:-10},'성적에 집중했지만 열정은 식었습니다.']]},
 {stages:['대학생·사회초년생'],emoji:'🎓',title:'등록금과 독립',desc:'{name}이 원하는 학교에 합격했지만 등록금과 자취비가 만만치 않습니다.',options:[['학비와 생활비를 모두 지원한다',{cash:-18000000,education:20,bond:10},'빚 없이 학업에 집중할 수 있게 됐습니다.'],['학비만 지원하고 생활비는 스스로 번다',{cash:-9000000,education:14,bond:6,happy:-2},'학업과 노동을 병행하며 단단해졌습니다.'],['학자금 대출을 스스로 책임지게 한다',{education:8,bond:-10,happy:-8},'독립은 빨랐지만 가족과 거리가 생겼습니다.']]},
 {stages:['대학생·사회초년생'],emoji:'💼',title:'첫 직장, 첫 퇴사 고민',desc:'{name}이 직장 내 괴롭힘 때문에 입사 석 달 만에 퇴사를 고민합니다.',options:[['건강을 우선해 그만두라고 한다',{cash:-3000000,bond:13,happy:12,health:8},'회복할 시간을 얻고 새 출발을 준비했습니다.'],['증거를 모아 정식 대응을 돕는다',{cash:-1000000,education:9,bond:10,happy:3},'자신을 지키는 현실적인 방법을 배웠습니다.'],['어디든 힘들다며 버티라고 한다',{bond:-13,happy:-15,health:-8},'직장은 지켰지만 마음이 크게 지쳤습니다.']]},
 {stages:['성인'],emoji:'🏠',title:'독립 자금 부탁',desc:'성인이 된 {name}이 전세 보증금 일부를 빌려 달라고 합니다.',options:[['증여 계약을 쓰고 지원한다',{cash:-30000000,bond:14,happy:8},'명확한 조건 덕분에 관계도 재정도 지켰습니다.'],['무이자로 빌려준다',{cash:-15000000,bond:8,happy:5},'부담을 나누며 독립을 응원했습니다.'],['스스로 모으라고 거절한다',{bond:-9,happy:-7,education:3},'독립은 늦어졌지만 재정 책임을 배웠습니다.']]},
 {stages:['성인'],emoji:'💍',title:'결혼을 앞둔 대화',desc:'{name}이 결혼과 가족 문제로 조언을 구합니다.',options:[['두 사람의 결정을 존중한다',{bond:15,happy:10},'간섭 대신 신뢰를 선택했습니다.'],['결혼 비용을 지원한다',{cash:-25000000,bond:12,happy:12},'새 가정의 출발에 든든한 힘이 됐습니다.'],['상대 조건을 따져 반대한다',{bond:-18,happy:-14},'걱정은 전했지만 오랫동안 연락이 뜸해졌습니다.']]},
];
function ensure(life){if(!life.childEventHistory)life.childEventHistory={};return life.childEventHistory;}
function make(life){ensure(life);const candidates=[];(life.children||[]).forEach(c=>EVENTS.forEach((e,i)=>{const stage=root.QT_FAMILY.stage(c);if(e.stages.includes(stage)&&(!e.traits||e.traits.includes(c.trait))){const key=c.id+':'+i,last=life.childEventHistory[key]||-999;if(c.ageMonths-last>=18)candidates.push({c,e,i,key});}}));if(!candidates.length)return null;const x=pick(candidates);life.childEventHistory[x.key]=x.c.ageMonths;return{cat:'family',emoji:x.e.emoji,title:`${x.c.name} · ${x.e.title}`,desc:x.e.desc.replace('{name}',x.c.name),childId:x.c.id,options:x.e.options.map(o=>({text:o[0],effects:{},childEffects:o[1],outcome:o[2]}))};}
function apply(life,childId,effects){const c=(life.children||[]).find(x=>x.id===childId);if(!c)return[];const changes=[];for(const k of ['bond','happy','health','education'])if(effects[k]!=null){c[k]=clamp((c[k]||0)+effects[k],0,k==='education'?999:100);changes.push(`${c.name} ${k} ${effects[k]>=0?'+':''}${effects[k]}`);}if(effects.talent){c.talent=effects.talent;changes.push(`재능 ${effects.talent}`);}life.familyBond=clamp((life.familyBond||0)+(effects.bond||0)*.25,0,100);return changes;}
root.QT_CHILD_EVENTS={EVENTS,ensure,make,apply};
})(window);
