/* QuickTrade Life — 수사·재판·형 집행 엔진 */
(function(root){'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function ensure(l){if(!l.justice)l.justice={case:null,probation:0,service:0,served:0,rehab:0};return l.justice;}
function openCase(l,crime,evidence,jail,fine){const j=ensure(l);j.case={crime,evidence,baseJail:jail,baseFine:fine,phase:'수사',months:1,lawyer:0,strategy:null};return j.case;}
function hire(l,tier){const c=ensure(l).case,t={public:[0,.05,'국선변호인'],standard:[5000000,.18,'형사 전문 변호사'],elite:[20000000,.32,'대형 로펌']}[tier];if(!c||!t)return null;c.lawyer=Math.max(c.lawyer,t[1]);c.lawyerName=t[2];return{cost:t[0],name:t[2]};}
function choose(l,s){const c=ensure(l).case;if(!c||c.phase!=='재판')return false;c.strategy=s;return true;}
function monthly(l,shield=0){const j=ensure(l),news=[];if(j.probation>0)j.probation--;if(j.service>0){j.service--;news.push('🧹 사회봉사 명령을 수행했습니다.');}if(l.jailMonths>0){j.served++;if(Math.random()<.2){j.rehab++;news.push('📚 교도소 교정교육에 참여했습니다.');}}const c=j.case;if(!c)return{news};if(--c.months>0)return{news};if(c.phase==='수사'){c.phase='기소';c.months=1;news.push(`🚔 ${c.crime} 사건이 검찰에 송치됐습니다.`);return{news};}if(c.phase==='기소'){if(Math.random()<.05+c.lawyer*.45+shield){j.case=null;news.push('✅ 증거 불충분으로 불기소됐습니다.');return{news,verdict:{dismissed:true}};}c.phase='재판';c.months=1;news.push('⚖️ 정식 기소됐습니다. 변호와 재판 전략을 선택하세요.');return{news};}if(!c.strategy){c.months=1;return{news};}const st={plea:[0,.4],contest:[.12,.05],cooperate:[.02,.55]}[c.strategy]||[0,0],acquit=clamp(.03+c.lawyer*.7+st[0]+shield-c.evidence*.25,.01,.75);if(Math.random()<acquit){j.case=null;news.push('🎉 무죄를 선고받았습니다.');return{news,verdict:{acquitted:true}};}const mit=clamp(st[1]+c.lawyer*.5+j.rehab*.01,0,.75),jm=Math.max(0,Math.ceil(c.baseJail*(1-mit))),fine=Math.max(0,Math.round(c.baseFine*(1-mit*.65))),suspended=jm<=3&&Math.random()<.55+c.lawyer;l.criminalRecord=(l.criminalRecord||0)+1;if(suspended){j.probation=12;j.service=4;}else l.jailMonths+=jm;j.case=null;news.push(`⚖️ 유죄 · 벌금 ${fine.toLocaleString()}원 · ${suspended?'집행유예·사회봉사':`징역 ${jm}개월`}`);return{news,verdict:{fine,jail:suspended?0:jm,suspended}};}
root.QT_JUSTICE={ensure,openCase,hire,choose,monthly};
})(window);
